# Generated by Django 5.2.12 on 2026-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("file_name", models.CharField(max_length=512)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("acr_status", models.CharField(default="", max_length=64)),
            ],
            options={
                "verbose_name": "Synced file",
                "verbose_name_plural": "Synced files",
                "ordering": ["-synced_at"],
            },
        ),
    ]
